include $(THEOS)/makefiles/common.mk

TWEAK_NAME = XoaInfoReconstructedPlug2
XoaInfoReconstructedPlug2_FILES = Tweak.xm XISwitcherWorker.m ../Shared/XIConfig.m
XoaInfoReconstructedPlug2_FRAMEWORKS = Foundation CoreFoundation
XoaInfoReconstructedPlug2_LIBRARIES = substrate
XoaInfoReconstructedPlug2_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
