include $(THEOS)/makefiles/common.mk

TWEAK_NAME = XoaInfoReconstructedPlug4
XoaInfoReconstructedPlug4_FILES = Tweak.xm XIPlug4StoreHooks.xm XIPlug4Workers.m ../Shared/XIConfig.m
XoaInfoReconstructedPlug4_FRAMEWORKS = Foundation UIKit
XoaInfoReconstructedPlug4_LIBRARIES = substrate
XoaInfoReconstructedPlug4_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
