/*
 * func-name: -[OptionVC .cxx_destruct]
 * func-address: 0x100686f24
 * export-type: decompile
 * callers: none
 * callees: 0x100798e00, 0x100798f08
 */

void __cdecl -[OptionVC .cxx_destruct](OptionVC *self, SEL a2)
{
  objc_destroyWeak((id *)&self->_textfAirplaneDelay);
  objc_destroyWeak((id *)&self->_btnOnOffAirplane);
  objc_destroyWeak((id *)&self->_imgOnOffAirplane);
  objc_destroyWeak((id *)&self->_imgKillAllApp);
  objc_destroyWeak((id *)&self->_btnKillAllApp);
  objc_destroyWeak((id *)&self->_imgPressUpdate);
  objc_storeStrong((id *)&self->_eSettingController, nullptr);
  objc_destroyWeak((id *)&self->_imageRadioBlockUDP);
  objc_destroyWeak((id *)&self->_textfBypassRRSFiles);
  objc_destroyWeak((id *)&self->_textfProxyPass);
  objc_destroyWeak((id *)&self->_textfProxyUser);
  objc_destroyWeak((id *)&self->_imgResetAppDataOnly);
  objc_destroyWeak((id *)&self->_imgOnOffAllowAlert);
  objc_destroyWeak((id *)&self->_btBlockWebGL);
  objc_destroyWeak((id *)&self->_imgWebGL);
  objc_destroyWeak((id *)&self->_imgWebRTC);
  objc_destroyWeak((id *)&self->_tfByPassDomains);
  objc_destroyWeak((id *)&self->_imgGhiDeRRS);
  objc_destroyWeak((id *)&self->_constraintViewIDFAURLHeigh);
  objc_destroyWeak((id *)&self->_labelPrivateAppstore);
  objc_destroyWeak((id *)&self->_labelPrivateVPN);
  objc_destroyWeak((id *)&self->_tfOldIDFAServerURL);
  objc_destroyWeak((id *)&self->_imageRadioHttp);
  objc_destroyWeak((id *)&self->_imageRadioSocks);
  objc_destroyWeak((id *)&self->_viewOldDevice);
  objc_destroyWeak((id *)&self->_viewVPNProxyIpGoc);
  objc_destroyWeak((id *)&self->_btnIPGoc);
  objc_destroyWeak((id *)&self->_labelIPGoc);
  objc_destroyWeak((id *)&self->_constraintPickerHeight2);
  objc_destroyWeak((id *)&self->_pickerServer);
  objc_destroyWeak((id *)&self->_constraintPickerHight);
  objc_destroyWeak((id *)&self->_viewForPicker);
  objc_destroyWeak((id *)&self->_btServerPicker);
  objc_destroyWeak((id *)&self->_constraintsAppstore);
  objc_destroyWeak((id *)&self->_viewDownloadAppstore);
  objc_destroyWeak((id *)&self->_tfAppStoreDelayOpenApp);
  objc_destroyWeak((id *)&self->_imgAutoRemoveApp);
  objc_destroyWeak((id *)&self->_btAutoRemoveApp);
  objc_destroyWeak((id *)&self->_imgAutoSaveRRS);
  objc_destroyWeak((id *)&self->_btAutoSaveRRS);
  objc_destroyWeak((id *)&self->_imgAppstoreDownload);
  objc_destroyWeak((id *)&self->_constraintHeighCheckProxy);
  objc_destroyWeak((id *)&self->_tfMinutesWait);
  objc_destroyWeak((id *)&self->_viewProxyCheckTime);
  objc_destroyWeak((id *)&self->_tfMinutesChangeIP);
  objc_destroyWeak((id *)&self->_tfPortCheckProxy);
  objc_destroyWeak((id *)&self->_tfipAddressCheckProxy);
  objc_destroyWeak((id *)&self->_imageCheckProxy);
  objc_destroyWeak((id *)&self->_imageNoteIpAdd);
  objc_destroyWeak((id *)&self->_tfDelayOpenApp);
  objc_destroyWeak((id *)&self->_scrollView);
  objc_destroyWeak((id *)&self->_txtfPort);
  objc_destroyWeak((id *)&self->_txtfIpAddress);
  objc_destroyWeak((id *)&self->_imageProxy);
  objc_destroyWeak((id *)&self->_imageJavaSafari);
  objc_destroyWeak((id *)&self->_imageVPNProxy);
  objc_destroyWeak((id *)&self->_imageXoaDataApp);
  objc_destroyWeak((id *)&self->_btnXoaDataApp);
  objc_destroyWeak((id *)&self->_imageXoaHeThong);
  objc_destroyWeak((id *)&self->_btnXoaHeThong);
  objc_destroyWeak((id *)&self->_imageXoaCache);
  objc_destroyWeak((id *)&self->_btnXoaCache);
  objc_destroyWeak((id *)&self->_viewXoaCache);
  objc_destroyWeak((id *)&self->_imageTatTool);
  objc_destroyWeak((id *)&self->_btnTatTool);
  objc_destroyWeak((id *)&self->_viewTatTool);
  objc_destroyWeak((id *)&self->_imageRespring);
  objc_destroyWeak((id *)&self->_btnRespring);
  objc_destroyWeak((id *)&self->_viewRespring);
  objc_destroyWeak((id *)&self->_imageTatPushNotifi);
  objc_destroyWeak((id *)&self->_btnTatPushNotifi);
  objc_destroyWeak((id *)&self->_viewTatPushNotifi);
  objc_destroyWeak((id *)&self->_imageTatAppLanDau);
  objc_destroyWeak((id *)&self->_btnTatAppLanDau);
  objc_destroyWeak((id *)&self->_viewTatAppLanDau);
  objc_destroyWeak((id *)&self->_imgDeleteAppReceipt);
  objc_destroyWeak((id *)&self->_btnDeleteAppReceipt);
  objc_destroyWeak((id *)&self->_tfPassIDFA);
  objc_destroyWeak((id *)&self->_tfUserNameIDFA);
  objc_destroyWeak((id *)&self->_imgOldIDFA);
  objc_destroyWeak((id *)&self->_btOldIDFA);
  objc_storeStrong((id *)&self->proxyType, nullptr);
  objc_storeStrong((id *)&self->pickerArray, nullptr);
  objc_storeStrong((id *)&self->z4dSB0wJ, nullptr);
  objc_storeStrong((id *)&self->AirPlaneDelaySecond, nullptr);
  objc_storeStrong((id *)&self->customIDFAServer, nullptr);
  objc_storeStrong((id *)&self->passOldIDFA, nullptr);
  objc_storeStrong((id *)&self->userNameOldIDFA, nullptr);
  objc_storeStrong((id *)&self->minutesWaitProxy, nullptr);
  objc_storeStrong((id *)&self->minutesCheckProxyTime, nullptr);
  objc_storeStrong((id *)&self->portCheckProxyTime, nullptr);
  objc_storeStrong((id *)&self->ipAddServerCheckProxyTime, nullptr);
  objc_storeStrong((id *)&self->t0LG05zQ, nullptr);
  objc_storeStrong((id *)&self->proxyPort, nullptr);
  objc_storeStrong((id *)&self->proxyIpAdd, nullptr);
  objc_storeStrong((id *)&self->proxyPass, nullptr);
  objc_storeStrong((id *)&self->proxyUser, nullptr);
  objc_storeStrong((id *)&self->k4djcPU9, nullptr);
  objc_storeStrong((id *)&self->z1DtCCU8, nullptr);
  objc_storeStrong((id *)&self->optionPressUpdate, nullptr);
  objc_storeStrong((id *)&self->optionBlockUDP, nullptr);
  objc_storeStrong((id *)&self->optionResetAppOnly, nullptr);
  objc_storeStrong((id *)&self->optionOnOffAllowAlert, nullptr);
  objc_storeStrong((id *)&self->v1ji8LCB, nullptr);
  objc_storeStrong((id *)&self->z2OOfeVK, nullptr);
  objc_storeStrong((id *)&self->optionGhiDeRRS, nullptr);
  objc_storeStrong((id *)&self->optionDeleteReceipt, nullptr);
  objc_storeStrong((id *)&self->appStoreDelayOpen, nullptr);
  objc_storeStrong((id *)&self->optionAutoRemoveApp, nullptr);
  objc_storeStrong((id *)&self->optionAutoSaveRRS, nullptr);
  objc_storeStrong((id *)&self->t1i5LFvw, nullptr);
  objc_storeStrong((id *)&self->optionAppStoreDownload, nullptr);
  objc_storeStrong((id *)&self->optionCheckIPChangeTime, nullptr);
  objc_storeStrong((id *)&self->optionNoteIPRRS, nullptr);
  objc_storeStrong((id *)&self->optionSetProxy, nullptr);
  objc_storeStrong((id *)&self->optionJavaSafari, nullptr);
  objc_storeStrong((id *)&self->optionVPNPro, nullptr);
  objc_storeStrong((id *)&self->optionXoaDataApp, nullptr);
  objc_storeStrong((id *)&self->optionXoaHeThong, nullptr);
  objc_storeStrong((id *)&self->i2XUXb92, nullptr);
  objc_storeStrong((id *)&self->optionTatPush, nullptr);
  objc_storeStrong((id *)&self->optionTatApp1Lab, nullptr);
  objc_storeStrong((id *)&self->b61mvQFk, nullptr);
  objc_storeStrong((id *)&self->e3pQLrWv, nullptr);
}
